### ISSUE TITLE
Verify Settings & Install Configuration Settings Issue

### ISSUE THREAD

**Issue by packtman** [rconfig/rconfig#30]
I followed all the steps as per the given installation guidelines. But, I am facing an issue with the Web UI. Clicking on the "Check Settings" button and "Install Database" button returns nothing?

Please let me know if I am missing something here or you need more information.
![rconfig](https://cloud.githubusercontent.com/assets/7194155/22663794/0b9a8fb0-ec7c-11e6-8fb4-6a6486b6c59e.PNG)

**Comment by sonerturgut50** [comment]
I am facing same problem. 
Please let me know if I am missing something here or you need more information.

**Comment by rconfig** [comment]
its a browser issue. I have verified this multiple times

**Comment by rideekulous** [comment]
I tried Chrome, Firefox 57, Firefox 52 ESR, IE, Edge.... should I install Opera? What's the fix?

**Comment by scott-abt** [comment]
This needs to be reopened @packtman I cannot get past this screen with IE, Firefox or Chrome. The javascript, it does nothing.

**Comment by gilpinb** [comment]
![image](https://user-images.githubusercontent.com/38253205/38561310-a2bf1ba0-3ccf-11e8-901e-569b7f7c007f.png)

I'm having the same issue, the software seems to download and run ok but when i attempt to install i can check settings and all is ok but i can't click the install database button or run the final check at the next page.

I've tried IE11, Chrome 65 and Firefox 59.

Is there a particular Java version needed?

**Comment by rconfig** [comment]
This issue should have been resolved in the latest 3.8.8 release. if not, please check next and let me know what happens. else, remove the /install from the URL and see if you get the login page.

thanks

**Comment by rconfig** [comment]
I've made 3.8.8 available via the install scripts. Please run those again. 

thanks

**Comment by gilpinb** [comment]
Hi Stephen,

I’ve tried re running the scripts but it didn’t help, I’ve tried wiping the CentOS virtual machine and starting from scratch again but I’m still getting the same thing, i.e. the check settings button works but the install database button doesn’t seem to do anything.

Thanks,
Barry

[cid:image001.png@01D3D1AA.15C5DAD0]
